# Generated by Django 5.0.1 on 2025-10-19 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('anime', '🎬 Anime'), ('serie', '📺 Serie'), ('pelicula', '🎥 Película'), ('manga', '📖 Manga'), ('manhwa', '📚 Manhwa'), ('libro', '📕 Libro'), ('videojuego', '🎮 Videojuego')], max_length=20)),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En Curso'), ('terminado', 'Terminado'), ('abandonado', 'Abandonado')], default='pendiente', max_length=20)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('progress', models.CharField(blank=True, max_length=100)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('external_link', models.URLField(blank=True)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('external_source', models.CharField(blank=True, max_length=50)),
                ('cover_image', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='entries', to='entries.tag')),
            ],
            options={
                'db_table': 'entries',
                'ordering': ['-updated_at'],
            },
        ),
    ]
