# Generated by Django 5.0.1 on 2025-10-19 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='progress',
        ),
        migrations.AddField(
            model_name='entry',
            name='progress_current',
            field=models.IntegerField(default=0, verbose_name='Progreso actual'),
        ),
        migrations.AddField(
            model_name='entry',
            name='progress_total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total'),
        ),
    ]
