# Generated by Django 5.0.1 on 2025-10-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entries", "0002_remove_entry_progress_entry_progress_current_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="duration_minutes",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="entry",
            name="episodes_count",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
